### ISSUE TITLE
Improve detection of moving vehicles

### ISSUE THREAD

**Issue by Luiggi33** [Pyenb/Smarty#1]
Hello there,
I remember you talking about the dataset issues, which includes the actual use in a live scenario where vehicles are often not still images. I have thought a bit about it and would suggest maybe automatically taking a few images from every batch and converting them into motion-blurred images. This shouldn't be too hard and can be implemented with some Python Code using OpenCV for example.
From what I know, this should replicate the conditions in a real environment, where a still camera takes images of moving vehicles.

**Comment by Pyenb** [comment]
Hey there,

Yeah, that sounds like a really good idea. I will look into that. That's also the reason I created the [Youtube analysis](https://github.com/Pyenb/Smarty/blob/master/data-collection/youtube_analysis.py) tool, which should also be helpful, as soon as the model is trained better. But until then this approach should work.

I also thought about starting the training process over, as I currently fear that I overtrained my model on my specific dataset, making it less accurate on new data.

I also plan on setting up a dashcam in my car, which will feed directly into the model and take a photo when a smart is detected, which I will then sort out manually later or connect it to a button that I or my passenger can press.
